services:
  - type: web
    name: imc-club-manager
    env: docker
    plan: standard
    autoDeploy: true
    disk:
      name: wordpress
      mountPath: /var/www/html
      sizeGB: 20
    envVars:
      - key: WORDPRESS_DB_HOST
        fromService:
          name: mysql-imc-club-manager
          type: pserv
          property: host
      - key: WORDPRESS_DB_NAME
        fromService:
          name: mysql-imc-club-manager
          type: pserv
          envVarKey: MYSQL_DATABASE
      - key: WORDPRESS_DB_USER
        fromService:
          name: mysql-imc-club-manager
          type: pserv
          envVarKey: MYSQL_USER
      - key: WORDPRESS_DB_PASSWORD
        fromService:
          name: mysql-imc-club-manager
          type: pserv
          envVarKey: MYSQL_PASSWORD

  - type: pserv
    name: mysql-imc-club-manager
    repo: https://github.com/render-examples/mysql.git
    env: docker
    plan: standard
    autoDeploy: false
    disk:
      name: mysql
      mountPath: /var/lib/mysql
      sizeGB: 20
    envVars:
      - key: MYSQL_DATABASE
        value: wordpress
      - key: MYSQL_USER
        value: wordpress
      - key: MYSQL_PASSWORD
        generateValue: true
      - key: MYSQL_ROOT_PASSWORD
        generateValue: true
